use AbstractVector in GenericExecutionStats
JuliaSmoothOptimizers/SolverCore.jl pull request #7
Opened 2021-04-13 14:47 UTC by geoffroyleconte

Hello, I would like to be able to add a `SparseVector` instead of a `Vector` in the `GenericExecutionStats`.

2021-04-13 14:53 UTC, dpo commented on src/stats.jl
> +  multipliers_U :: AbstractVector # zU
It's not a good idea to put abstract types inside structs: https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type. One solution is to parameterize the struct.

2021-04-13 15:00 UTC, abelsiqueira commented on src/stats.jl
> +  multipliers_U :: AbstractVector # zU
As you suggested in another topic, we can also just remove the type.

2021-04-13 15:54 UTC, dpo commented on src/stats.jl
> +  multipliers_U :: AbstractVector # zU
But then I also found https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type. So that answers my question.

2021-04-13 15:56 UTC, dpo commented on src/stats.jl
> +mutable struct GenericExecutionStats{T<:Real} <: AbstractExecutionStats
What I meant is
```julia
mutable struct GenericExecutionStats{V <: AbstractVector} <: AbstractExecutionStats
  # ...
  solution :: V
  # ... etc.
```
The disadvantage is that all vectors must have the same type.

2021-04-13 16:36 UTC, geoffroyleconte commented on src/stats.jl
> +mutable struct GenericExecutionStats{T<:Real} <: AbstractExecutionStats
Yes I don't want that they have the same type. The current solution is not convenient? I don't know why the CI fails with some packages

2021-04-19 14:34 UTC, dpo commented on src/stats.jl
> +                               solution :: V1=eltype(nlp.meta.x0)[],
In the constructor, I think the types should be `AbstractVector` because we want them to be “vector-like”.

2021-04-19 14:34 UTC, dpo commented on src/stats.jl
> +  return GenericExecutionStats{V1, V2, V3, V4}(status, solution, objective, dual_feas, primal_feas,
Yes, this is correct!

2021-04-19 14:34 UTC, dpo commented on src/stats.jl
> +function disp_vector(io :: IO, x :: V) where V
AbstractVector here too.

2021-04-19 15:00 UTC, geoffroyleconte commented on src/stats.jl
> +                               solution :: V1=eltype(nlp.meta.x0)[],
I don't understand. Then what is the use of using V1, V2... if we give `AbstractVector{T}` ? Or do you mean only `AbstractVector` alone (without `T`)? In this case we loose type specialisation and the function will be slower no?

2021-04-19 15:12 UTC, dpo commented on src/stats.jl
> +                               solution :: V1=eltype(nlp.meta.x0)[],
It’s inside the struct that you don’t want abstract types. In function arguments, they’re desirable.

2021-04-19 15:32 UTC, geoffroyleconte commented on src/stats.jl
> +                               solution :: V1=eltype(nlp.meta.x0)[],
OK! So `AbstractVector{T}` or `AbstractVector` ? If `AbstractVector{T}`, then some tests with CaNNOLeS.jl and DerivativeFreeSolvers.jl may fail because they output the solution in different Float precisions, but this may be better for the user because he will probably want to have all the same Float type in the `GenericExecutionStats`

2021-04-19 15:32 UTC, abelsiqueira commented on src/stats.jl
> +  return GenericExecutionStats{V1, V2, V3, V4}(status, solution, objective, dual_feas, primal_feas,
Isn't this overkill? In the new SolverCore I'm using `{T, V}`, with `T` for types and `V` for container types. Krylov is using this as well.

2021-04-19 15:41 UTC, geoffroyleconte commented on src/stats.jl
> +  return GenericExecutionStats{V1, V2, V3, V4}(status, solution, objective, dual_feas, primal_feas,
@abelsiqueira with RipQP I need to return `multipliers_L` and `multipliers_U` as `SparseVector` because they may have a lot of zero values, and `solution`and `multipliers` as `Vector`

2021-04-20 04:27 UTC, dpo commented on src/stats.jl
> +                               solution :: V1=eltype(nlp.meta.x0)[],
I agree. I think AbstractVector{T}.

2021-04-20 14:16 UTC, dpo approved these changes

2021-04-22 23:48 UTC, dpo commented
@abelsiqueira How do you feel about this in light of our meeting today?

2021-04-23 01:19 UTC, abelsiqueira commented
I would recommend using the change to remove the types of multipliers and test if it affects the performance of SolverBenchmark's `solve_problems`.
Either way, I would test type stability with `@code_warntype`.

2021-04-23 02:42 UTC, geoffroyleconte commented
If we remove the types of multipliers, will it will be slower if we use solvers in-place in a for loop for example ? 
I'll try to make some benchmarks but I cannot test it in-place with RipQP for now

2021-04-26 23:15 UTC, geoffroyleconte commented
@abelsiqueira I made the changes you proposed. I changed the inputs of the outer constructor with `AbstractArray` because @dpo mentionned semi-definite programming (I think this is necessary, but correct me if this is not needed). 
I you both agree with these changes I would like to increment the version to 0.1.1 in my next commit.

Some tests fail with CaNNOLeS.jl and DerivativeFreeSolvers.jl because they return multipliers in a different precision than `solution`.

2021-05-14 19:47 UTC, dpo commented
@abelsiqueira Any objections to merging this?

2021-05-14 19:53 UTC, dpo commented
@abelsiqueira Is it expected that Cannoles tries to call
```
MethodError: no method matching var"#GenericExecutionStats#3"(::Vector{Float16}, ::Float16, ::Float16, ::Float16, ::Vector{Float64}, ::Vector{Float64}, ::Vector{Float64}, ::Int64, ::Float64, ::Dict{Symbol, Any}, ::Type{SolverCore.GenericExecutionStats}, ::Symbol, ::ADNLSModel)
```
i.e., with a `Vector{Float16}` solution vector and `Vector{Float64}` multipliers?

2021-05-14 20:06 UTC, abelsiqueira commented
I just checked the CaNNOLeS code and it doesn't use the updated multipliers output, i.e., it still passes the multipliers as `solver_specific`. That means that the default value for `multipliers` is `Vector{Float64}`. Here is the line: https://github.com/JuliaSmoothOptimizers/SolverCore.jl/pull/7/files#diff-4707ffacbf76401dc918e8bfac5bf57023ff087628a2b6d2b741f943d972fa1cR83
It should probably depend on something other than `x0`?

2021-05-14 20:13 UTC, abelsiqueira requested changes
Let me know what you think.

2021-05-14 20:13 UTC, abelsiqueira commented on src/stats.jl
>  function GenericExecutionStats(
This should probably change to `GenericExecutionStats{T, V}`, and there should be a new constructor
```
function GenericExecutionStats(status::Symbol, nlp::AbstractNLPModel; kwargs...)
	T = eltype(nlp.meta.x0)
	V = typeof(nlp.meta.x0)
	return GenericExecutionStats{T, V}(status, nlp; kwargs...)
end
```

2021-05-14 20:13 UTC, abelsiqueira commented on src/stats.jl
> +  solution::AbstractArray{T} = eltype(nlp.meta.x0)[],
```suggestion
  solution::V = T[],
```

2021-05-14 20:13 UTC, abelsiqueira commented on src/stats.jl
> +  dual_feas::T = eltype(solution)(Inf),
```suggestion
  objective::T = T(Inf),
  dual_feas::T = T(Inf),
```

2021-05-14 20:13 UTC, abelsiqueira commented on src/stats.jl
> +  multipliers_U::AbstractArray{T} = eltype(nlp.meta.x0)[],
```suggestion
  multipliers::AbstractArray = V(undef, 0),
  multipliers_L::AbstractArray = V(undef, 0),
  multipliers_U::AbstractArray = V(undef, 0),
```

2021-05-14 20:13 UTC, abelsiqueira commented on src/stats.jl
> +  return GenericExecutionStats{T, V}(
```suggestion
  return GenericExecutionStats{T, V}(
```

2021-05-14 21:03 UTC, dpo commented on src/stats.jl
> +  solution::AbstractArray{T} = eltype(nlp.meta.x0)[],
Doesn't this implicitly enforce `V == Vector{T}`?

2021-05-14 21:07 UTC, abelsiqueira commented on src/stats.jl
> +  solution::AbstractArray{T} = eltype(nlp.meta.x0)[],
Only if no `solution` is passed.

2021-05-14 23:27 UTC, geoffroyleconte commented on src/stats.jl
> +  solution::AbstractArray{T} = eltype(nlp.meta.x0)[],
But then we will have `where {T<:Real, V, Tsp}` for this outer constructor, I don't think that it's possible to create a vector `T[]` since `T` will be deducted from the arguments

2021-05-15 01:11 UTC, geoffroyleconte commented
@abelsiqueira is this what you meant? The tests are still failing because `T= eltype(nlp.meta.x0)`, but I'm not sure I understood well

2021-05-17 13:40 UTC, abelsiqueira commented on src/stats.jl
> +end
```suggestion
function GenericExecutionStats(
  status::Symbol,
  nlp::AbstractNLPModel;
  solution::V = eltype(nlp.meta.x0)[],
  kwargs...
) where V
	T = eltype(solution)
	return GenericExecutionStats{T, V}(status, nlp; solution=solution, kwargs...)
end
```
It needed more information. I tested with [this](https://gist.github.com/abelsiqueira/1597884bd2c9f52369b41b18fd222865). Unfortunately, I don't have access to CUArrays to test with different `V`s.

2021-05-18 14:35 UTC, geoffroyleconte commented on src/stats.jl
> +end
Than you! I just tested your example in a google collab with CUDA and it worked

```
using SolverCore, NLPModels, CUDA

mutable struct DummyModel <: AbstractNLPModel
  meta :: AbstractNLPModelMeta
  counters :: Counters
end

DummyModel() = DummyModel(NLPModelMeta(2, x0=zeros(2)), Counters())

#%%
nlp = DummyModel()

output = GenericExecutionStats(:unknown, nlp)
print(output)

#%%
x = CUDA.ones(Float64, 2)
output = GenericExecutionStats(:unknown, nlp, solution=x)
print(output)

#%%
output = GenericExecutionStats(:unknown, nlp, solution=x, dual_feas=one(Float64))
print(output)
```

2021-05-18 17:55 UTC, abelsiqueira approved these changes

2021-05-18 17:56 UTC, merged

2021-05-18 17:56 UTC, abelsiqueira commented
Thanks.